PSNC-Cloud.Web.Sample/Controllers/CallApiController.cs
using IdentityModel.Client;
using Newtonsoft.Json.Linq;
using System;
using System.Configuration;
using System.IO;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PSNCCloud.Web.Sample.Controllers
{
    public class CallApiController : Controller
    {
        // GET: CallApi/ClientCredentials
        public async Task<ActionResult> ClientCredentials()
        {
            var response = await GetTokenAsync();
            var result = await CallApi(response.AccessToken);

            ViewBag.Json = result;
            return View("ShowApiResult");
        }

        // GET: CallApi/UserCredentials
        public async Task<ActionResult> UserCredentials()
        {
            var user = User as ClaimsPrincipal;
            var token = user.FindFirst("access_token").Value;
            var result = await CallApi(token);

            ViewBag.Json = result;
            return View("ShowApiResult");
        }

        private async Task<string> CallApi(string token)
        {
            var client = new HttpClient();
            client.SetBearerToken(token);

            

            //var json = await client.GetStringAsync(ConfigurationManager.AppSettings["BaseApiUrl"] + "identity");
            //var json = await client.GetStringAsync(ConfigurationManager.AppSettings["BaseApiUrl"] + endpoint);
            //return JArray.Parse(json).ToString();

            StringContent bodyContent = new StringContent(@"
[
    {
        ""PriceItemIndex"":1,
        ""FinancialPeriodID"":201712,
        ""contractorCode"":""FA641"",
        ""formNumber"":1,
        ""itemNumber"":1,
        ""subItemNumber"":1,
        ""groupType"":2,
        ""productCode"":""34730511000001105"",
        ""quantity"":1,
        ""endorsementCodes"":""NB""
    },
    
     {
        ""PriceItemIndex"":2,
        ""FinancialPeriodID"":201712,
        ""contractorCode"":""FA641"",
        ""formNumber"":1,
        ""itemNumber"":1,
        ""subItemNumber"":1,
        ""groupType"":2,
        ""productCode"":""34730511000001105"",
        ""quantity"":1,
        ""endorsementCodes"":""NB""
    }
]
");
            bodyContent.Headers.Remove("Content-Type");
            bodyContent.Headers.Add("Content-Type", "application/json");

            string endpoint = "/v1/sqlstoredprocedures/priceitems";
            HttpResponseMessage responseMessage = await client.PostAsync(ConfigurationManager.AppSettings["BaseApiUrl"] + endpoint, bodyContent);
            //HttpResponseMessage responseMessage = await client.GetAsync(ConfigurationManager.AppSettings["BaseApiUrl"] + endpoint);

            string jsonMessage;
            using (Stream responseStream = await responseMessage.Content.ReadAsStreamAsync())
            {
                jsonMessage = new StreamReader(responseStream).ReadToEnd();
            }

            try
            {
                return JArray.Parse(jsonMessage).ToString();
            }
            catch (Exception ex)
            {
                return jsonMessage.ToString();
            }
        }

        private async Task<TokenResponse> GetTokenAsync()
        {
            var client = new TokenClient(
                ConfigurationManager.AppSettings["BaseAuthUrl"] + "core/connect/token",
                "mvc_service",
                "secret");

            return await client.RequestClientCredentialsAsync("psncapi");
        }
    }
}

PSNC-Cloud.Web.Sample/Controllers/HomeController.cs
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Thinktecture.IdentityModel.Mvc;

namespace PSNCCloud.Web.Sample.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult About()
        {
            return View((User as ClaimsPrincipal).Claims);
        }

        [ResourceAuthorize("Read", "ContactDetails")]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HandleForbidden]
        public ActionResult UpdateContact()
        {
            if (!HttpContext.CheckAccess("Write", "ContactDetails", "some more data"))
            {
                return this.AccessDenied();
            }

            ViewBag.Message = "Upate your contact details!";
            return View();
        }

        public ActionResult Logout()
        {
            Request.GetOwinContext().Authentication.SignOut();
            return Redirect("/");
        }
    }
}

PSNC-Cloud.Web.Sample/Views/CallApi/ShowApiResult.cshtml
<h2>Result</h2>

<pre>@ViewBag.Json</pre>

PSNC-Cloud.Web.Sample/Views/Home/About.cshtml
@model IEnumerable<System.Security.Claims.Claim>

<dl>
    @foreach (var claim in Model)
    {
        <dt>@claim.Type</dt>
        <dd>@claim.Value</dd>
    }
</dl>

PSNC-Cloud.Web.Sample/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PSNC-Cloud.Web.Sample/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PSNC-Cloud.Web.Sample/Views/Shared/Forbidden.cshtml
@{
    ViewBag.Title = "Forbidden";
}

<h1>Forbidden</h1>

PSNC-Cloud.Web.Sample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Login", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Call API (Client)", "ClientCredentials", "CallApi")</li>
                        <li>@Html.ActionLink("Call API (User)", "UserCredentials", "CallApi")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                    }
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>